apiVersion: v1
kind: Service
metadata:
  name: lab5-web-service
  labels:
    app: lab5-web
spec:
  selector:
    app: lab5-web
  ports:
    - name: http
      protocol: TCP
      port: 80       # port externe
      targetPort: 5000  # port du container backend
  type: LoadBalancer
